### ISSUE TITLE
add feature pls

### ISSUE THREAD

**Issue by Rifkichrl** [dCodeX21/taiko-trailblazers-weth-swap#1]
please help add a feature for the amount of eth that we will send so that it is not random, and also add it so that it can be swapped to usdc or taiko tokens

**Comment by dCodeX21** [comment]
Hi, thank you for your interest with the script. I'm afraid swapping such stable coins or tokens are not possible as involves contracts with the DeFi platform. The contract used here is basically for the basic wrapping and unwrapping of ETH in Taiko Network. But we can add an option to allow random eth or fixed eth to be swapped.

**Comment by dCodeX21** [comment]
Will probably update in the future. Still looking for easy way to implement human readable values input.
